Feature: Playground (instant visual prototyping)
  The playground is a pre-scaffolded vite + react + tailwind site rendered on
  the room screen. Page generation is delegated to the fastest available
  code model (chatjimmy at ~17k tokens/sec, with fallbacks) so a spoken
  request becomes a rendered page in seconds. Claude agents can later deepen
  the same files.

  Background:
    Given the playground dev server is running with HMR
    And the jimmy proxy is reachable

  Scenario: Pages are files, routing is automatic
    When a file "src/pages/pricing.tsx" exists exporting a default component
    Then the page is reachable at "/pricing" without any manual route wiring
    And the index page lists all existing pages

  Scenario: write_page creates a complete page in seconds
    When the write_page tool is called with path "pricing" and a description
    Then a complete valid TSX file is generated by the speed model
    And the file uses tailwind classes with a modern dark aesthetic
    And the page renders without runtime errors
    And the elapsed time from tool call to file written is under 10 seconds

  Scenario: edit_page modifies an existing page preserving the rest
    Given a page "pricing" already exists
    When the edit_page tool is called with instructions "add a third tier called Enterprise"
    Then the current file content is sent to the speed model as context
    And the rewritten file still contains the unchanged sections
    And the page hot-reloads in the browser without a full refresh

  Scenario: Generated code is validated before being written
    When the speed model returns code for a page
    Then the gateway validates it parses as TSX
    And invalid output triggers one retry with the error appended
    And a second failure falls back to the next model in the chain

  Scenario: write_page and edit_page drive the room screen themselves
    When write_page or edit_page succeeds for path "pricing"
    Then connected consoles receive a "tokenmaxxer.navigate" event for "/pricing"

  Scenario: open_page returns to an existing page
    Given a page "pricing" exists
    When the open_page tool is called with path "pricing"
    Then connected consoles receive a "tokenmaxxer.navigate" event
    And the playground preview shows "/pricing"

  Scenario: Tools teach the model instead of failing silently
    When open_page is called for a page that does not exist
    Then the tool result says the page is missing, lists existing pages
      and points to write_page
    When write_page targets the protected "home" index
    Then the tool result refuses and asks for a descriptive new slug

  Scenario: Model choice is grounded in measurements
    Given an evaluation dataset of representative page requests
    When the codegen experiment runs against jimmy and the fallback models
    Then latency and judge-scored quality are recorded per model
    And the default model chain is ordered by what the data shows
